#!/usr/bin/env bash
# Launch Zed editor using nix run

# This script works around direnv's limitation with GUI apps
# and the fact that zed-editor isn't in our devshell
exec nix run nixpkgs#zed-editor -- "$@"